services:
  - type: web
    name: Ecoffee
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: daphne Ecoffee.asgi:application --port $PORT --bind 0.0.0.0
    staticPublishPath: ./staticfiles
