# Generated by Django 5.1.5 on 2025-02-24 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('coffee_until_earned', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('badge_image', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('number_of_visits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('active_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cups_saved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_active_date_time', models.DateTimeField(blank=True, null=True)),
                ('default_badge_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoffeeBase.badge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('most_recent_shop_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoffeeBase.shop')),
            ],
        ),
        migrations.CreateModel(
            name='user_badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_obtained', models.DateTimeField(blank=True, null=True)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.custom_user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'badge_id'), name='unique_user_badge')],
            },
        ),
        migrations.CreateModel(
            name='user_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_amounts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.custom_user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'shop_id'), name='unique_user_shop')],
            },
        ),
    ]
