# Generated by Django 5.1.5 on 2025-02-24 11:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoffeeBase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupsSaved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lastActiveDateTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='badge',
            name='coffeeUntilEarned',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='numberOfVisits',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='defaultBadgeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoffeeBase.badge'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mostRecentShopId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EcoffeeBase.shop'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.customuser'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcoffeeBase.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
