# Generated by Django 5.1.6 on 2025-02-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoffeeBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_image',
            field=models.CharField(default='defaultbadge.png', max_length=255),
        ),
    ]
