# Generated by Django 5.1.5 on 2025-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcoffeeBase', '0002_customuser_delete_coffee_badge_badge_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userbadge',
            name='uniqueUserBadge',
        ),
        migrations.RemoveConstraint(
            model_name='usershop',
            name='uniqueUserShop',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='badgeId',
            new_name='badge_id',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='coffeeUntilEarned',
            new_name='coffee_until_earned',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='cupsSaved',
            new_name='cups_saved',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='defaultBadgeId',
            new_name='default_badge_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastActiveDateTime',
            new_name='last_active_date_time',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mostRecentShopId',
            new_name='most_recent_shop_id',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='activeCode',
            new_name='active_code',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='numberOfVisits',
            new_name='number_of_visits',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopId',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shopName',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='badgeId',
            new_name='badge_id',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='dateTimeObtained',
            new_name='date_time_obtained',
        ),
        migrations.RenameField(
            model_name='usershop',
            old_name='shopId',
            new_name='shop_id',
        ),
        migrations.RenameField(
            model_name='usershop',
            old_name='visitAmounts',
            new_name='visit_amounts',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='owned',
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge_id'), name='unique_user_badge'),
        ),
        migrations.AddConstraint(
            model_name='usershop',
            constraint=models.UniqueConstraint(fields=('user', 'shop_id'), name='unique_user_shop'),
        ),
    ]
