# Generated by Django 5.1.5 on 2025-02-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoffeeBase', '0003_remove_userbadge_uniqueuserbadge_and_more'),
        ('EcoffeeBase', '0004_remove_userbadge_uniqueuserbadge_and_more'),
    ]

    operations = [
    ]
