# Generated by Django 5.1.6 on 2025-03-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EcoffeeBase', '0002_alter_badge_badge_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='shop_logos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='EcoffeeBase.shop')),
            ],
        ),
    ]
